export const englishCatalog = Object.freeze({
	'app.name': 'Tiempio',
	'app.tagline': 'Make the music you can already hear.',
	'app.desktop': 'Desktop studio',
	'app.web': 'Web sketchbook',
	'common.close': 'Close',
	'common.open': 'Open',
	'common.back': 'Back',
	'common.add': 'Add',
	'common.more': 'More',
	'common.settings': 'Settings',
	'common.language': 'Language',
	'common.theme': 'Appearance',
	'common.system': 'System',
	'common.light': 'Light',
	'common.dark': 'Dark',
	'common.notAvailable': 'Not available yet',
	'nav.home': 'Home',
	'nav.piano': 'Piano roll',
	'nav.drums': 'Drums',
	'nav.arrangement': 'Arrangement',
	'nav.soundSculpt': 'Sound sculpt',
	'nav.layers': 'Layers',
	'nav.context': 'Context',
	'home.eyebrow': 'Electronic music studio',
	'home.title': 'Start with a feeling.',
	'home.description': 'Build a first loop without translating your idea into engineering.',
	'home.newProject': 'Create a new piece',
	'home.openProject': 'Open a project',
	'home.recent': 'Recent pieces',
	'home.empty': 'Your recent pieces will live here.',
	'firstLayer.eyebrow': 'A quiet first step',
	'firstLayer.title': 'What should carry the idea?',
	'firstLayer.description': 'Choose a musical role. You can change the sound at any moment.',
	'firstLayer.melody': 'Melody',
	'firstLayer.chords': 'Chords',
	'firstLayer.bass': 'Bass',
	'firstLayer.drums': 'Rhythm',
	'soundChooser.title': 'Choose a character',
	'soundChooser.description': 'Sounds are grouped by feeling before synthesis vocabulary.',
	'soundChooser.warm': 'Warm',
	'soundChooser.clear': 'Clear',
	'soundChooser.deep': 'Deep',
	'soundChooser.grainy': 'Grainy',
	'soundChooser.preview': 'Preview sound',
	'pianoRoll.title': 'Piano roll',
	'pianoRoll.subtitle': 'Shape the phrase',
	'pianoRoll.addNote': 'Add note',
	'pianoRoll.velocity': 'Energy',
	'drums.title': 'Drums',
	'drums.subtitle': 'Build the pulse',
	'drums.kick': 'Kick',
	'drums.snare': 'Snare',
	'drums.hat': 'Hi-hat',
	'drums.clap': 'Clap',
	'arrangement.title': 'Arrangement',
	'arrangement.subtitle': 'Give the idea a journey',
	'arrangement.intro': 'Intro',
	'arrangement.main': 'Main',
	'arrangement.break': 'Break',
	'arrangement.outro': 'Outro',
	'sculpt.title': 'Sound sculpt',
	'sculpt.subtitle': 'Describe motion, weight and space',
	'sculpt.brightness': 'Brightness',
	'sculpt.movement': 'Movement',
	'sculpt.space': 'Space',
	'sculpt.texture': 'Texture',
	'layers.title': 'Layers',
	'layers.add': 'Add layer',
	'layers.melody': 'Glass melody',
	'layers.chords': 'Warm chords',
	'layers.bass': 'Low pulse',
	'layers.drums': 'Soft drums',
	'context.title': 'Details',
	'context.sound': 'Sound',
	'context.feel': 'Feel',
	'context.pattern': 'Pattern',
	'context.velocity': 'Energy',
	'transport.play': 'Play',
	'transport.pause': 'Pause',
	'transport.stop': 'Stop',
	'transport.record': 'Record',
	'transport.tempo': 'Tempo',
	'transport.position': 'Position',
	'transport.loop': 'Loop',
	'transport.audioShared': 'Shared audio',
	'window.minimize': 'Minimize window',
	'window.maximize': 'Maximize window',
	'window.restore': 'Restore window',
	'window.close': 'Close window',
	'layout.openNavigation': 'Open navigation',
	'layout.openContext': 'Open details',
	'layout.closeDrawer': 'Close panel',
	'command.palette': 'Command palette',
	'command.shortcut': 'Shortcut: {shortcut}'
} as const)

export type LocalizationKey = keyof typeof englishCatalog
export type LocalizationCatalog = Readonly<Record<LocalizationKey, string>>

export const russianCatalog = Object.freeze({
	'app.name': 'Tiempio',
	'app.tagline': 'Создай музыку, которую уже слышишь внутри.',
	'app.desktop': 'Студия для компьютера',
	'app.web': 'Веб-скетчбук',
	'common.close': 'Закрыть',
	'common.open': 'Открыть',
	'common.back': 'Назад',
	'common.add': 'Добавить',
	'common.more': 'Ещё',
	'common.settings': 'Настройки',
	'common.language': 'Язык',
	'common.theme': 'Оформление',
	'common.system': 'Системное',
	'common.light': 'Светлое',
	'common.dark': 'Тёмное',
	'common.notAvailable': 'Пока недоступно',
	'nav.home': 'Главная',
	'nav.piano': 'Пиано-ролл',
	'nav.drums': 'Ударные',
	'nav.arrangement': 'Аранжировка',
	'nav.soundSculpt': 'Скульптор звука',
	'nav.layers': 'Слои',
	'nav.context': 'Параметры',
	'home.eyebrow': 'Студия электронной музыки',
	'home.title': 'Начни с ощущения.',
	'home.description': 'Собери первый луп, не переводя идею на язык звукорежиссуры.',
	'home.newProject': 'Создать новую композицию',
	'home.openProject': 'Открыть проект',
	'home.recent': 'Недавние композиции',
	'home.empty': 'Здесь появятся недавние композиции.',
	'firstLayer.eyebrow': 'Спокойный первый шаг',
	'firstLayer.title': 'Что станет основой идеи?',
	'firstLayer.description': 'Выбери музыкальную роль. Звук можно изменить в любой момент.',
	'firstLayer.melody': 'Мелодия',
	'firstLayer.chords': 'Аккорды',
	'firstLayer.bass': 'Бас',
	'firstLayer.drums': 'Ритм',
	'soundChooser.title': 'Выбери характер',
	'soundChooser.description': 'Звуки сначала собраны по ощущениям, а не по терминам синтеза.',
	'soundChooser.warm': 'Тёплый',
	'soundChooser.clear': 'Ясный',
	'soundChooser.deep': 'Глубокий',
	'soundChooser.grainy': 'Зернистый',
	'soundChooser.preview': 'Прослушать звук',
	'pianoRoll.title': 'Пиано-ролл',
	'pianoRoll.subtitle': 'Придай фразе форму',
	'pianoRoll.addNote': 'Добавить ноту',
	'pianoRoll.velocity': 'Энергия',
	'drums.title': 'Ударные',
	'drums.subtitle': 'Собери пульс',
	'drums.kick': 'Бочка',
	'drums.snare': 'Малый барабан',
	'drums.hat': 'Хай-хэт',
	'drums.clap': 'Хлопок',
	'arrangement.title': 'Аранжировка',
	'arrangement.subtitle': 'Преврати идею в историю',
	'arrangement.intro': 'Вступление',
	'arrangement.main': 'Основная часть',
	'arrangement.break': 'Пауза',
	'arrangement.outro': 'Финал',
	'sculpt.title': 'Скульптор звука',
	'sculpt.subtitle': 'Опиши движение, вес и пространство',
	'sculpt.brightness': 'Яркость',
	'sculpt.movement': 'Движение',
	'sculpt.space': 'Пространство',
	'sculpt.texture': 'Текстура',
	'layers.title': 'Слои',
	'layers.add': 'Добавить слой',
	'layers.melody': 'Стеклянная мелодия',
	'layers.chords': 'Тёплые аккорды',
	'layers.bass': 'Низкий пульс',
	'layers.drums': 'Мягкие ударные',
	'context.title': 'Параметры',
	'context.sound': 'Звук',
	'context.feel': 'Характер',
	'context.pattern': 'Паттерн',
	'context.velocity': 'Энергия',
	'transport.play': 'Воспроизвести',
	'transport.pause': 'Пауза',
	'transport.stop': 'Остановить',
	'transport.record': 'Записать',
	'transport.tempo': 'Темп',
	'transport.position': 'Позиция',
	'transport.loop': 'Зациклить',
	'transport.audioShared': 'Общее аудио',
	'window.minimize': 'Свернуть окно',
	'window.maximize': 'Развернуть окно',
	'window.restore': 'Восстановить окно',
	'window.close': 'Закрыть окно',
	'layout.openNavigation': 'Открыть навигацию',
	'layout.openContext': 'Открыть параметры',
	'layout.closeDrawer': 'Закрыть панель',
	'command.palette': 'Палитра команд',
	'command.shortcut': 'Сочетание клавиш: {shortcut}'
} as const satisfies LocalizationCatalog)

export const catalogs = Object.freeze({
	en: englishCatalog,
	ru: russianCatalog
})
