export const englishCatalog = Object.freeze({
	'app.name': 'Tiempio',
	'app.tagline': 'Make the music you can already hear.',
	'app.desktop': 'Desktop studio',
	'app.web': 'Web sketchbook',
	'common.close': 'Close',
	'common.open': 'Open',
	'common.back': 'Back',
	'common.add': 'Add',
	'common.more': 'More',
	'common.settings': 'Settings',
	'common.language': 'Language',
	'common.theme': 'Appearance',
	'common.system': 'System',
	'common.light': 'Light',
	'common.dark': 'Dark',
	'common.notAvailable': 'Not available yet',
	'common.loading': 'Loading view…',
	'nav.studio': 'Studio',
	'nav.home': 'Home',
	'nav.piano': 'Piano roll',
	'nav.drums': 'Drums',
	'nav.arrangement': 'Arrangement',
	'nav.soundSculpt': 'Sound sculpt',
	'nav.layers': 'Layers',
	'nav.context': 'Context',
	'home.eyebrow': 'Electronic music, without the ceremony',
	'home.title': 'Start with a feeling.',
	'home.titleLead': 'Start with one',
	'home.titleEmphasis': 'sound.',
	'home.description':
		'Tiempio opens like an instrument, not an exam. No mandatory templates, routing or empty technical tracks — only a clear first step.',
	'home.newProject': 'New track',
	'home.newProjectDescription': 'An empty eight-bar phrase',
	'home.startWithSound': 'Start with a sound',
	'home.startWithSoundDescription': 'Choose the instrument character first',
	'home.untitledProject': 'Untitled track',
	'home.openProject': 'Open a project',
	'home.openProjectDescription': 'A local Tiempio file',
	'home.recent': 'Recent',
	'home.recentNight': 'Today, 14:23 · A minor',
	'home.recentQuiet': 'Yesterday · C minor',
	'home.recentGlass': '4 days ago · F minor',
	'home.inspirationTitle': 'Listen to references in parallel.',
	'home.inspirationDescription':
		'Tiempio shares system audio with the browser, Spotify and other applications by default.',
	'home.empty': 'Your recent pieces will live here.',
	'home.recentDetail': '{{bpm}} BPM · {{count}} layers',
	'project.savedLocally': 'Saved locally',
	'firstLayer.eyebrow': 'A quiet first step',
	'firstLayer.title': 'Where should we begin?',
	'firstLayer.description':
		'Choose a musical role and Tiempio will create a fitting instrument, range and editor. No empty MIDI tracks.',
	'firstLayer.melody': 'Melody',
	'firstLayer.chords': 'Chords or melody',
	'firstLayer.bass': 'Bass',
	'firstLayer.drums': 'Rhythm',
	'firstLayer.melodyDescription': 'A line to remember',
	'firstLayer.chordsDescription': 'Notes with harmony guidance',
	'firstLayer.bassDescription': 'Low end and movement',
	'firstLayer.drumsDescription': 'Hits and pulse',
	'firstLayer.upload': 'My sound',
	'firstLayer.uploadDescription': 'Drop an audio file',
	'firstLayer.footerGuidance': 'The first layer can be replaced at any time',
	'firstLayer.quickAction': 'Quick action',
	'soundChooser.title': 'Choose a character',
	'soundChooser.subtitle': 'The sound can be changed later',
	'soundChooser.instrument': 'Instrument',
	'soundChooser.deepBassDescription':
		'Low, smooth and steady. It opens in the bass range, so the first note lands where you expect it.',
	'soundChooser.useSound': 'Use sound',
	'soundChooser.auditionHint': 'Hold A–L to play',
	'soundChooser.presetDeep': 'Massive and even',
	'soundChooser.presetPunchy': 'Short and readable',
	'soundChooser.presetWarm': 'Soft and rounded',
	'soundChooser.presetDirty': 'Rough and saturated',
	'soundChooser.presetSoft': 'Calm and airy',
	'soundChooser.presetRetro': 'Distinctly synthetic',
	'soundChooser.keyboardPreview': 'Keyboard preview',
	'soundChooser.fineTune': 'Fine tuning',
	'soundChooser.semanticHelp':
		'No oscillators on the first screen. These axes control several synthesis parameters together and change the sound predictably.',
	'soundChooser.description': 'Sounds are grouped by feeling before synthesis vocabulary.',
	'soundChooser.palette': 'Palette 01',
	'soundChooser.warm': 'Warm',
	'soundChooser.clear': 'Clear',
	'soundChooser.deep': 'Deep',
	'soundChooser.grainy': 'Grainy',
	'soundChooser.preview': 'Preview sound',
	'soundChooser.feltSignalDescription': 'Soft edge · close and human',
	'soundChooser.clearGlassDescription': 'Open top · patient decay',
	'soundChooser.lowEmberDescription': 'Dense center · quiet movement',
	'soundChooser.paperStarsDescription': 'Dry texture · uneven glow',
	'pianoRoll.title': 'Piano roll',
	'pianoRoll.subtitle': 'Shape the phrase',
	'pianoRoll.addNote': 'Add note',
	'pianoRoll.velocity': 'Energy',
	'pianoRoll.noteAtBeat': '{{pitch}}, beat {{beat}}',
	'pianoRoll.hint': 'Tab moves through notes · Enter removes the selected note',
	'pianoRoll.octaveDown': 'One octave down',
	'pianoRoll.octaveUp': 'One octave up',
	'pianoRoll.scaleNotes': 'Scale notes',
	'pianoRoll.selectedNote': 'Selected note',
	'pianoRoll.selectedNoteTitle': 'C2 — stable.',
	'pianoRoll.selectedNoteDescription':
		'This is the third degree of the current Am chord. It supports the harmony well.',
	'pianoRoll.nextVariant': 'Next variant',
	'pianoRoll.nextVariantDescription':
		'The ghost note shows a suggestion. Press it to add it, or ignore it.',
	'pianoRoll.grid': 'Grid',
	'pianoRoll.length': 'Length',
	'pianoRoll.fourBars': '4 bars',
	'pianoRoll.rest': 'rest',
	'pianoRoll.repeat': 'Repeat',
	'pianoRoll.split': 'Split',
	'drums.title': 'Drums',
	'drums.subtitle': 'Build the pulse',
	'drums.kick': 'Kick',
	'drums.snare': 'Snare',
	'drums.hat': 'Hi-hat',
	'drums.clap': 'Clap',
	'drums.steps': '{{count}} steps',
	'drums.stepLabel': '{{instrument}}, step {{step}}',
	'drums.hint': 'Tab moves through steps · Space toggles a hit',
	'drums.patternDescription':
		'A steady electronic pulse. Press the dots directly or take the base and change it.',
	'drums.patternStraight': 'even',
	'drums.patternSparse': 'more air',
	'drums.patternDriving': 'more movement',
	'drums.patternBroken': 'uneven pattern',
	'arrangement.title': 'Arrangement',
	'arrangement.subtitle': 'Give the idea a journey',
	'arrangement.intro': 'Intro',
	'arrangement.main': 'Main',
	'arrangement.break': 'Break',
	'arrangement.outro': 'Outro',
	'arrangement.bars': '{{count}} bars',
	'sculpt.title': 'Sound sculpt',
	'sculpt.subtitle': 'Describe motion, weight and space',
	'sculpt.brightness': 'Brightness',
	'sculpt.movement': 'Movement',
	'sculpt.space': 'Space',
	'sculpt.texture': 'Texture',
	'layers.title': 'Layers',
	'layers.add': 'Add layer',
	'layers.melody': 'Glass melody',
	'layers.chords': 'Warm chords',
	'layers.bass': 'Low pulse',
	'layers.drums': 'Soft drums',
	'context.title': 'Details',
	'context.noLayer': 'No layer selected',
	'context.sound': 'Sound',
	'context.feel': 'Feel',
	'context.pattern': 'Pattern',
	'context.velocity': 'Energy',
	'context.feltSignalDescription': 'Warm · soft edge',
	'context.clearGlassDescription': 'Clear · patient decay',
	'context.lowEmberDescription': 'Deep · quiet movement',
	'context.enginePending': 'Changes stay gentle until the audio engine is connected.',
	'transport.play': 'Play',
	'transport.pause': 'Pause',
	'transport.stop': 'Stop',
	'transport.record': 'Record',
	'transport.tempo': 'Tempo',
	'transport.position': 'Position',
	'transport.loop': 'Loop',
	'transport.toolbar': 'Transport',
	'transport.previous': 'Previous',
	'transport.next': 'Next',
	'transport.sharedAudio': 'Shared audio',
	'transport.audioOffline': 'Audio unavailable',
	'engine.available': 'Audio capability available',
	'engine.unavailable': 'Audio engine unavailable',
	'settings.sessionOnly': 'Saved for this session',
	'settings.loading': 'Saving settings',
	'settings.saved': 'Settings saved',
	'settings.failed': 'Settings could not be saved',
	'window.minimize': 'Minimize window',
	'window.controls': 'Window controls',
	'window.maximize': 'Maximize window',
	'window.restore': 'Restore window',
	'window.close': 'Close window',
	'layout.openNavigation': 'Open navigation',
	'layout.openContext': 'Open details',
	'layout.closeDrawer': 'Close panel',
	'command.palette': 'Command palette',
	'command.shortcut': 'Shortcut: {{shortcut}}',
	'command.disabled.unavailable': 'This command is unavailable.',
	'command.disabled.engineUnavailable': 'The audio engine is not available yet.',
	'command.disabled.projectUnavailable': 'Open or create a project to use this command.',
	'command.disabled.noDrawer': 'No panel is open.'
} as const)

export type LocalizationKey = keyof typeof englishCatalog
export type LocalizationCatalog = Readonly<Record<LocalizationKey, string>>

export const russianCatalog = Object.freeze({
	'app.name': 'Tiempio',
	'app.tagline': 'Создай музыку, которую уже слышишь внутри.',
	'app.desktop': 'Студия для компьютера',
	'app.web': 'Веб-скетчбук',
	'common.close': 'Закрыть',
	'common.open': 'Открыть',
	'common.back': 'Назад',
	'common.add': 'Добавить',
	'common.more': 'Ещё',
	'common.settings': 'Настройки',
	'common.language': 'Язык',
	'common.theme': 'Оформление',
	'common.system': 'Системное',
	'common.light': 'Светлое',
	'common.dark': 'Тёмное',
	'common.notAvailable': 'Пока недоступно',
	'common.loading': 'Загрузка раздела…',
	'nav.studio': 'Студия',
	'nav.home': 'Главная',
	'nav.piano': 'Пиано-ролл',
	'nav.drums': 'Ударные',
	'nav.arrangement': 'Аранжировка',
	'nav.soundSculpt': 'Скульптор звука',
	'nav.layers': 'Слои',
	'nav.context': 'Параметры',
	'home.eyebrow': 'Electronic music, without the ceremony',
	'home.title': 'Начни с ощущения.',
	'home.titleLead': 'Начни с одного',
	'home.titleEmphasis': 'звука.',
	'home.description':
		'Tiempio открывается как инструмент, а не как экзамен. Никаких обязательных шаблонов, маршрутизации и пустых технических дорожек — только понятный первый шаг.',
	'home.newProject': 'Новый трек',
	'home.newProjectDescription': 'Пустая восьмитактовая фраза',
	'home.startWithSound': 'Начать со звука',
	'home.startWithSoundDescription': 'Сначала выбрать характер инструмента',
	'home.untitledProject': 'Новый трек',
	'home.openProject': 'Открыть проект',
	'home.openProjectDescription': 'Локальный файл Tiempio',
	'home.recent': 'Недавние',
	'home.recentNight': 'Сегодня, 14:23 · A minor',
	'home.recentQuiet': 'Вчера · C minor',
	'home.recentGlass': '4 дня назад · F minor',
	'home.inspirationTitle': 'Слушай референсы параллельно.',
	'home.inspirationDescription':
		'Tiempio по умолчанию делит системный звук с браузером, Spotify и другими приложениями.',
	'home.empty': 'Здесь появятся недавние композиции.',
	'home.recentDetail': '{{bpm}} BPM · {{count}} слоёв',
	'project.savedLocally': 'Сохранено локально',
	'firstLayer.eyebrow': 'Спокойный первый шаг',
	'firstLayer.title': 'С чего начнём?',
	'firstLayer.description':
		'Выбирай музыкальную роль, а Tiempio сам создаст подходящий инструмент, диапазон и редактор. Никаких пустых MIDI-дорожек.',
	'firstLayer.melody': 'Мелодия',
	'firstLayer.chords': 'Аккорды или мелодия',
	'firstLayer.bass': 'Бас',
	'firstLayer.drums': 'Ритм',
	'firstLayer.melodyDescription': 'Линия, которую хочется запомнить',
	'firstLayer.chordsDescription': 'Ноты с подсказками по гармонии',
	'firstLayer.bassDescription': 'Низ и движение',
	'firstLayer.drumsDescription': 'Удары и пульс',
	'firstLayer.upload': 'Мой звук',
	'firstLayer.uploadDescription': 'Перетащить аудиофайл',
	'firstLayer.footerGuidance': 'Первый слой можно заменить в любой момент',
	'firstLayer.quickAction': 'Быстрое действие',
	'soundChooser.title': 'Выбери характер',
	'soundChooser.subtitle': 'Звук можно изменить позже',
	'soundChooser.instrument': 'Инструмент',
	'soundChooser.deepBassDescription':
		'Низкий, гладкий и устойчивый. Сразу открывается в басовом диапазоне, поэтому первая сыгранная нота звучит там, где ожидается.',
	'soundChooser.useSound': 'Использовать звук',
	'soundChooser.auditionHint': 'Удерживай A–L для игры',
	'soundChooser.presetDeep': 'Массивный и ровный',
	'soundChooser.presetPunchy': 'Короткий и читаемый',
	'soundChooser.presetWarm': 'Мягкий и округлый',
	'soundChooser.presetDirty': 'Грубый и насыщенный',
	'soundChooser.presetSoft': 'Спокойный и воздушный',
	'soundChooser.presetRetro': 'Выраженный синтовый',
	'soundChooser.keyboardPreview': 'Предпросмотр клавиатуры',
	'soundChooser.fineTune': 'Тонкая настройка',
	'soundChooser.semanticHelp':
		'Никаких осцилляторов на первом экране. Эти оси управляют несколькими параметрами синтеза одновременно и меняют звук предсказуемо.',
	'soundChooser.description': 'Звуки сначала собраны по ощущениям, а не по терминам синтеза.',
	'soundChooser.palette': 'Палитра 01',
	'soundChooser.warm': 'Тёплый',
	'soundChooser.clear': 'Ясный',
	'soundChooser.deep': 'Глубокий',
	'soundChooser.grainy': 'Зернистый',
	'soundChooser.preview': 'Прослушать звук',
	'soundChooser.feltSignalDescription': 'Мягкий край · близкий и живой',
	'soundChooser.clearGlassDescription': 'Открытый верх · спокойное затухание',
	'soundChooser.lowEmberDescription': 'Плотный центр · тихое движение',
	'soundChooser.paperStarsDescription': 'Сухая текстура · неровное свечение',
	'pianoRoll.title': 'Пиано-ролл',
	'pianoRoll.subtitle': 'Придай фразе форму',
	'pianoRoll.addNote': 'Добавить ноту',
	'pianoRoll.velocity': 'Энергия',
	'pianoRoll.noteAtBeat': '{{pitch}}, доля {{beat}}',
	'pianoRoll.hint': 'Tab перемещает по нотам · Enter удаляет выбранную ноту',
	'pianoRoll.octaveDown': 'На октаву ниже',
	'pianoRoll.octaveUp': 'На октаву выше',
	'pianoRoll.scaleNotes': 'Ноты гаммы',
	'pianoRoll.selectedNote': 'Выбранная нота',
	'pianoRoll.selectedNoteTitle': 'C2 — устойчиво.',
	'pianoRoll.selectedNoteDescription':
		'Это третья ступень текущего аккорда Am. Она хорошо поддерживает гармонию.',
	'pianoRoll.nextVariant': 'Следующий вариант',
	'pianoRoll.nextVariantDescription':
		'Призрачная нота показывает предложение. Нажми её, чтобы добавить, или проигнорируй.',
	'pianoRoll.grid': 'Сетка',
	'pianoRoll.length': 'Длина',
	'pianoRoll.fourBars': '4 такта',
	'pianoRoll.rest': 'пауза',
	'pianoRoll.repeat': 'Повторить',
	'pianoRoll.split': 'Разделить',
	'drums.title': 'Ударные',
	'drums.subtitle': 'Собери пульс',
	'drums.kick': 'Бочка',
	'drums.snare': 'Малый барабан',
	'drums.hat': 'Хай-хэт',
	'drums.clap': 'Хлопок',
	'drums.steps': '{{count}} шагов',
	'drums.stepLabel': '{{instrument}}, шаг {{step}}',
	'drums.hint': 'Tab перемещает по шагам · Пробел включает удар',
	'drums.patternDescription':
		'Ровный электронный пульс. Нажимай точки напрямую или возьми основу и измени её.',
	'drums.patternStraight': 'равномерно',
	'drums.patternSparse': 'больше воздуха',
	'drums.patternDriving': 'больше движения',
	'drums.patternBroken': 'неровный рисунок',
	'arrangement.title': 'Аранжировка',
	'arrangement.subtitle': 'Преврати идею в историю',
	'arrangement.intro': 'Вступление',
	'arrangement.main': 'Основная часть',
	'arrangement.break': 'Пауза',
	'arrangement.outro': 'Финал',
	'arrangement.bars': '{{count}} тактов',
	'sculpt.title': 'Скульптор звука',
	'sculpt.subtitle': 'Опиши движение, вес и пространство',
	'sculpt.brightness': 'Яркость',
	'sculpt.movement': 'Движение',
	'sculpt.space': 'Пространство',
	'sculpt.texture': 'Текстура',
	'layers.title': 'Слои',
	'layers.add': 'Добавить слой',
	'layers.melody': 'Стеклянная мелодия',
	'layers.chords': 'Тёплые аккорды',
	'layers.bass': 'Низкий пульс',
	'layers.drums': 'Мягкие ударные',
	'context.title': 'Параметры',
	'context.noLayer': 'Слой не выбран',
	'context.sound': 'Звук',
	'context.feel': 'Характер',
	'context.pattern': 'Паттерн',
	'context.velocity': 'Энергия',
	'context.feltSignalDescription': 'Тёплый · мягкий край',
	'context.clearGlassDescription': 'Ясный · плавное затухание',
	'context.lowEmberDescription': 'Глубокий · спокойное движение',
	'context.enginePending': 'Изменения остаются мягкими, пока аудиодвижок не подключён.',
	'transport.play': 'Воспроизвести',
	'transport.pause': 'Пауза',
	'transport.stop': 'Остановить',
	'transport.record': 'Записать',
	'transport.tempo': 'Темп',
	'transport.position': 'Позиция',
	'transport.loop': 'Зациклить',
	'transport.toolbar': 'Транспорт',
	'transport.previous': 'Назад',
	'transport.next': 'Вперёд',
	'transport.sharedAudio': 'Shared audio',
	'transport.audioOffline': 'Аудио недоступно',
	'engine.available': 'Аудиовозможности доступны',
	'engine.unavailable': 'Аудиодвижок недоступен',
	'settings.sessionOnly': 'Сохранено на эту сессию',
	'settings.loading': 'Настройки сохраняются',
	'settings.saved': 'Настройки сохранены',
	'settings.failed': 'Не удалось сохранить настройки',
	'window.minimize': 'Свернуть окно',
	'window.controls': 'Управление окном',
	'window.maximize': 'Развернуть окно',
	'window.restore': 'Восстановить окно',
	'window.close': 'Закрыть окно',
	'layout.openNavigation': 'Открыть навигацию',
	'layout.openContext': 'Открыть параметры',
	'layout.closeDrawer': 'Закрыть панель',
	'command.palette': 'Палитра команд',
	'command.shortcut': 'Сочетание клавиш: {{shortcut}}',
	'command.disabled.unavailable': 'Эта команда недоступна.',
	'command.disabled.engineUnavailable': 'Аудиодвижок пока недоступен.',
	'command.disabled.projectUnavailable':
		'Откройте или создайте проект, чтобы использовать эту команду.',
	'command.disabled.noDrawer': 'Ни одна панель не открыта.'
} as const satisfies LocalizationCatalog)

export const spanishCatalog = Object.freeze({
	'app.name': 'Tiempio',
	'app.tagline': 'Crea la música que ya puedes oír.',
	'app.desktop': 'Estudio de escritorio',
	'app.web': 'Bloc de ideas web',
	'common.close': 'Cerrar',
	'common.open': 'Abrir',
	'common.back': 'Volver',
	'common.add': 'Añadir',
	'common.more': 'Más',
	'common.settings': 'Ajustes',
	'common.language': 'Idioma',
	'common.theme': 'Apariencia',
	'common.system': 'Sistema',
	'common.light': 'Claro',
	'common.dark': 'Oscuro',
	'common.notAvailable': 'Aún no disponible',
	'common.loading': 'Cargando vista…',
	'nav.studio': 'Estudio',
	'nav.home': 'Inicio',
	'nav.piano': 'Piano roll',
	'nav.drums': 'Batería',
	'nav.arrangement': 'Arreglo',
	'nav.soundSculpt': 'Escultura sonora',
	'nav.layers': 'Capas',
	'nav.context': 'Contexto',
	'home.eyebrow': 'Electronic music, without the ceremony',
	'home.title': 'Empieza con una sensación.',
	'home.titleLead': 'Empieza con un',
	'home.titleEmphasis': 'sonido.',
	'home.description':
		'Tiempio se abre como un instrumento, no como un examen. Sin plantillas obligatorias, ruteo ni pistas técnicas vacías: solo un primer paso claro.',
	'home.newProject': 'Pista nueva',
	'home.newProjectDescription': 'Una frase vacía de ocho compases',
	'home.startWithSound': 'Empezar con un sonido',
	'home.startWithSoundDescription': 'Elegir primero el carácter del instrumento',
	'home.untitledProject': 'Pista sin título',
	'home.openProject': 'Abrir un proyecto',
	'home.openProjectDescription': 'Un archivo local de Tiempio',
	'home.recent': 'Recientes',
	'home.recentNight': 'Hoy, 14:23 · A minor',
	'home.recentQuiet': 'Ayer · C minor',
	'home.recentGlass': 'Hace 4 días · F minor',
	'home.inspirationTitle': 'Escucha referencias en paralelo.',
	'home.inspirationDescription':
		'Tiempio comparte por defecto el audio del sistema con el navegador, Spotify y otras aplicaciones.',
	'home.empty': 'Tus piezas recientes aparecerán aquí.',
	'home.recentDetail': '{{bpm}} BPM · {{count}} capas',
	'project.savedLocally': 'Guardado localmente',
	'firstLayer.eyebrow': 'Un primer paso tranquilo',
	'firstLayer.title': '¿Por dónde empezamos?',
	'firstLayer.description':
		'Elige un papel musical y Tiempio creará el instrumento, el registro y el editor adecuados. Sin pistas MIDI vacías.',
	'firstLayer.melody': 'Melodía',
	'firstLayer.chords': 'Acordes o melodía',
	'firstLayer.bass': 'Bajo',
	'firstLayer.drums': 'Ritmo',
	'firstLayer.melodyDescription': 'Una línea para recordar',
	'firstLayer.chordsDescription': 'Notas con guía de armonía',
	'firstLayer.bassDescription': 'Graves y movimiento',
	'firstLayer.drumsDescription': 'Golpes y pulso',
	'firstLayer.upload': 'Mi sonido',
	'firstLayer.uploadDescription': 'Soltar un archivo de audio',
	'firstLayer.footerGuidance': 'La primera capa se puede reemplazar en cualquier momento',
	'firstLayer.quickAction': 'Acción rápida',
	'soundChooser.title': 'Elige un carácter',
	'soundChooser.subtitle': 'El sonido se puede cambiar después',
	'soundChooser.instrument': 'Instrumento',
	'soundChooser.deepBassDescription':
		'Grave, suave y estable. Se abre directamente en el registro del bajo para que la primera nota suene donde esperas.',
	'soundChooser.useSound': 'Usar sonido',
	'soundChooser.auditionHint': 'Mantén A–L para tocar',
	'soundChooser.presetDeep': 'Masivo y uniforme',
	'soundChooser.presetPunchy': 'Corto y legible',
	'soundChooser.presetWarm': 'Suave y redondo',
	'soundChooser.presetDirty': 'Áspero y saturado',
	'soundChooser.presetSoft': 'Calmo y aireado',
	'soundChooser.presetRetro': 'Marcadamente sintético',
	'soundChooser.keyboardPreview': 'Vista previa del teclado',
	'soundChooser.fineTune': 'Ajuste fino',
	'soundChooser.semanticHelp':
		'No hay osciladores en la primera pantalla. Estos ejes controlan varios parámetros de síntesis a la vez y cambian el sonido de forma predecible.',
	'soundChooser.description':
		'Los sonidos se agrupan por sensaciones antes que por términos de síntesis.',
	'soundChooser.palette': 'Paleta 01',
	'soundChooser.warm': 'Cálido',
	'soundChooser.clear': 'Claro',
	'soundChooser.deep': 'Profundo',
	'soundChooser.grainy': 'Granulado',
	'soundChooser.preview': 'Escuchar sonido',
	'soundChooser.feltSignalDescription': 'Borde suave · cercano y humano',
	'soundChooser.clearGlassDescription': 'Agudos abiertos · caída paciente',
	'soundChooser.lowEmberDescription': 'Centro denso · movimiento sereno',
	'soundChooser.paperStarsDescription': 'Textura seca · brillo irregular',
	'pianoRoll.title': 'Piano roll',
	'pianoRoll.subtitle': 'Da forma a la frase',
	'pianoRoll.addNote': 'Añadir nota',
	'pianoRoll.velocity': 'Energía',
	'pianoRoll.noteAtBeat': '{{pitch}}, pulso {{beat}}',
	'pianoRoll.hint': 'Tab recorre las notas · Enter elimina la nota seleccionada',
	'pianoRoll.octaveDown': 'Una octava abajo',
	'pianoRoll.octaveUp': 'Una octava arriba',
	'pianoRoll.scaleNotes': 'Notas de la escala',
	'pianoRoll.selectedNote': 'Nota seleccionada',
	'pianoRoll.selectedNoteTitle': 'C2 — estable.',
	'pianoRoll.selectedNoteDescription':
		'Es el tercer grado del acorde Am actual. Sostiene bien la armonía.',
	'pianoRoll.nextVariant': 'Siguiente variante',
	'pianoRoll.nextVariantDescription':
		'La nota fantasma muestra una sugerencia. Púlsala para añadirla o ignórala.',
	'pianoRoll.grid': 'Cuadrícula',
	'pianoRoll.length': 'Duración',
	'pianoRoll.fourBars': '4 compases',
	'pianoRoll.rest': 'pausa',
	'pianoRoll.repeat': 'Repetir',
	'pianoRoll.split': 'Dividir',
	'drums.title': 'Batería',
	'drums.subtitle': 'Construye el pulso',
	'drums.kick': 'Bombo',
	'drums.snare': 'Caja',
	'drums.hat': 'Charles',
	'drums.clap': 'Palmada',
	'drums.steps': '{{count}} pasos',
	'drums.stepLabel': '{{instrument}}, paso {{step}}',
	'drums.hint': 'Tab recorre los pasos · Espacio activa un golpe',
	'drums.patternDescription':
		'Un pulso electrónico uniforme. Pulsa los puntos directamente o parte de la base y cámbiala.',
	'drums.patternStraight': 'uniforme',
	'drums.patternSparse': 'más aire',
	'drums.patternDriving': 'más movimiento',
	'drums.patternBroken': 'patrón irregular',
	'arrangement.title': 'Arreglo',
	'arrangement.subtitle': 'Dale un recorrido a la idea',
	'arrangement.intro': 'Introducción',
	'arrangement.main': 'Parte principal',
	'arrangement.break': 'Pausa',
	'arrangement.outro': 'Final',
	'arrangement.bars': '{{count}} compases',
	'sculpt.title': 'Escultura sonora',
	'sculpt.subtitle': 'Describe movimiento, peso y espacio',
	'sculpt.brightness': 'Brillo',
	'sculpt.movement': 'Movimiento',
	'sculpt.space': 'Espacio',
	'sculpt.texture': 'Textura',
	'layers.title': 'Capas',
	'layers.add': 'Añadir capa',
	'layers.melody': 'Melodía de cristal',
	'layers.chords': 'Acordes cálidos',
	'layers.bass': 'Pulso grave',
	'layers.drums': 'Batería suave',
	'context.title': 'Detalles',
	'context.noLayer': 'Ninguna capa seleccionada',
	'context.sound': 'Sonido',
	'context.feel': 'Carácter',
	'context.pattern': 'Patrón',
	'context.velocity': 'Energía',
	'context.feltSignalDescription': 'Cálido · borde suave',
	'context.clearGlassDescription': 'Claro · caída paciente',
	'context.lowEmberDescription': 'Profundo · movimiento sereno',
	'context.enginePending':
		'Los cambios se mantienen suaves hasta que se conecte el motor de audio.',
	'transport.play': 'Reproducir',
	'transport.pause': 'Pausa',
	'transport.stop': 'Detener',
	'transport.record': 'Grabar',
	'transport.tempo': 'Tempo',
	'transport.position': 'Posición',
	'transport.loop': 'Bucle',
	'transport.toolbar': 'Transporte',
	'transport.previous': 'Anterior',
	'transport.next': 'Siguiente',
	'transport.sharedAudio': 'Audio compartido',
	'transport.audioOffline': 'Audio no disponible',
	'engine.available': 'Audio disponible',
	'engine.unavailable': 'Motor de audio no disponible',
	'settings.sessionOnly': 'Guardado durante esta sesión',
	'settings.loading': 'Guardando ajustes',
	'settings.saved': 'Ajustes guardados',
	'settings.failed': 'No se pudieron guardar los ajustes',
	'window.minimize': 'Minimizar ventana',
	'window.controls': 'Controles de ventana',
	'window.maximize': 'Maximizar ventana',
	'window.restore': 'Restaurar ventana',
	'window.close': 'Cerrar ventana',
	'layout.openNavigation': 'Abrir navegación',
	'layout.openContext': 'Abrir detalles',
	'layout.closeDrawer': 'Cerrar panel',
	'command.palette': 'Paleta de comandos',
	'command.shortcut': 'Atajo: {{shortcut}}',
	'command.disabled.unavailable': 'Este comando no está disponible.',
	'command.disabled.engineUnavailable': 'El motor de audio aún no está disponible.',
	'command.disabled.projectUnavailable': 'Abre o crea un proyecto para usar este comando.',
	'command.disabled.noDrawer': 'No hay ningún panel abierto.'
} as const satisfies LocalizationCatalog)

export const catalogs = Object.freeze({
	en: englishCatalog,
	ru: russianCatalog,
	es: spanishCatalog
})
