export const englishCatalog = Object.freeze({
	'app.name': 'Tiempio',
	'app.tagline': 'Make the music you can already hear.',
	'app.desktop': 'Desktop studio',
	'app.web': 'Web sketchbook',
	'common.close': 'Close',
	'common.open': 'Open',
	'common.back': 'Back',
	'common.add': 'Add',
	'common.more': 'More',
	'common.settings': 'Settings',
	'common.language': 'Language',
	'common.theme': 'Appearance',
	'common.system': 'System',
	'common.light': 'Light',
	'common.dark': 'Dark',
	'common.notAvailable': 'Not available yet',
	'nav.studio': 'Studio',
	'nav.home': 'Home',
	'nav.piano': 'Piano roll',
	'nav.drums': 'Drums',
	'nav.arrangement': 'Arrangement',
	'nav.soundSculpt': 'Sound sculpt',
	'nav.layers': 'Layers',
	'nav.context': 'Context',
	'home.eyebrow': 'Electronic music studio',
	'home.title': 'Start with a feeling.',
	'home.description': 'Build a first loop without translating your idea into engineering.',
	'home.newProject': 'Create a new piece',
	'home.openProject': 'Open a project',
	'home.recent': 'Recent pieces',
	'home.empty': 'Your recent pieces will live here.',
	'home.recentDetail': '{{bpm}} BPM · {{count}} layers',
	'firstLayer.eyebrow': 'A quiet first step',
	'firstLayer.title': 'What should carry the idea?',
	'firstLayer.description': 'Choose a musical role. You can change the sound at any moment.',
	'firstLayer.melody': 'Melody',
	'firstLayer.chords': 'Chords',
	'firstLayer.bass': 'Bass',
	'firstLayer.drums': 'Rhythm',
	'firstLayer.melodyDescription': 'A line to remember',
	'firstLayer.chordsDescription': 'Color and emotional weight',
	'firstLayer.bassDescription': 'A grounded pulse',
	'firstLayer.drumsDescription': 'Movement and time',
	'soundChooser.title': 'Choose a character',
	'soundChooser.description': 'Sounds are grouped by feeling before synthesis vocabulary.',
	'soundChooser.palette': 'Palette 01',
	'soundChooser.warm': 'Warm',
	'soundChooser.clear': 'Clear',
	'soundChooser.deep': 'Deep',
	'soundChooser.grainy': 'Grainy',
	'soundChooser.preview': 'Preview sound',
	'soundChooser.feltSignalDescription': 'Soft edge · close and human',
	'soundChooser.clearGlassDescription': 'Open top · patient decay',
	'soundChooser.lowEmberDescription': 'Dense center · quiet movement',
	'soundChooser.paperStarsDescription': 'Dry texture · uneven glow',
	'pianoRoll.title': 'Piano roll',
	'pianoRoll.subtitle': 'Shape the phrase',
	'pianoRoll.addNote': 'Add note',
	'pianoRoll.velocity': 'Energy',
	'pianoRoll.noteAtBeat': '{{pitch}}, beat {{beat}}',
	'pianoRoll.hint': 'Tab moves through notes · Enter removes the selected note',
	'drums.title': 'Drums',
	'drums.subtitle': 'Build the pulse',
	'drums.kick': 'Kick',
	'drums.snare': 'Snare',
	'drums.hat': 'Hi-hat',
	'drums.clap': 'Clap',
	'drums.steps': '{{count}} steps',
	'drums.stepLabel': '{{instrument}}, step {{step}}',
	'drums.hint': 'Tab moves through steps · Space toggles a hit',
	'arrangement.title': 'Arrangement',
	'arrangement.subtitle': 'Give the idea a journey',
	'arrangement.intro': 'Intro',
	'arrangement.main': 'Main',
	'arrangement.break': 'Break',
	'arrangement.outro': 'Outro',
	'arrangement.bars': '{{count}} bars',
	'sculpt.title': 'Sound sculpt',
	'sculpt.subtitle': 'Describe motion, weight and space',
	'sculpt.brightness': 'Brightness',
	'sculpt.movement': 'Movement',
	'sculpt.space': 'Space',
	'sculpt.texture': 'Texture',
	'layers.title': 'Layers',
	'layers.add': 'Add layer',
	'layers.melody': 'Glass melody',
	'layers.chords': 'Warm chords',
	'layers.bass': 'Low pulse',
	'layers.drums': 'Soft drums',
	'context.title': 'Details',
	'context.sound': 'Sound',
	'context.feel': 'Feel',
	'context.pattern': 'Pattern',
	'context.velocity': 'Energy',
	'context.feltSignalDescription': 'Warm · soft edge',
	'context.clearGlassDescription': 'Clear · patient decay',
	'context.lowEmberDescription': 'Deep · quiet movement',
	'context.enginePending': 'Changes stay gentle until the audio engine is connected.',
	'transport.play': 'Play',
	'transport.pause': 'Pause',
	'transport.stop': 'Stop',
	'transport.record': 'Record',
	'transport.tempo': 'Tempo',
	'transport.position': 'Position',
	'transport.loop': 'Loop',
	'transport.audioShared': 'Shared audio',
	'transport.toolbar': 'Transport',
	'engine.ready': 'Audio engine status: ready',
	'settings.sessionOnly': 'Saved for this session',
	'settings.loading': 'Saving settings',
	'settings.saved': 'Settings saved',
	'settings.failed': 'Settings could not be saved',
	'window.minimize': 'Minimize window',
	'window.controls': 'Window controls',
	'window.maximize': 'Maximize window',
	'window.restore': 'Restore window',
	'window.close': 'Close window',
	'layout.openNavigation': 'Open navigation',
	'layout.openContext': 'Open details',
	'layout.closeDrawer': 'Close panel',
	'command.palette': 'Command palette',
	'command.shortcut': 'Shortcut: {{shortcut}}'
} as const)

export type LocalizationKey = keyof typeof englishCatalog
export type LocalizationCatalog = Readonly<Record<LocalizationKey, string>>

export const russianCatalog = Object.freeze({
	'app.name': 'Tiempio',
	'app.tagline': 'Создай музыку, которую уже слышишь внутри.',
	'app.desktop': 'Студия для компьютера',
	'app.web': 'Веб-скетчбук',
	'common.close': 'Закрыть',
	'common.open': 'Открыть',
	'common.back': 'Назад',
	'common.add': 'Добавить',
	'common.more': 'Ещё',
	'common.settings': 'Настройки',
	'common.language': 'Язык',
	'common.theme': 'Оформление',
	'common.system': 'Системное',
	'common.light': 'Светлое',
	'common.dark': 'Тёмное',
	'common.notAvailable': 'Пока недоступно',
	'nav.studio': 'Студия',
	'nav.home': 'Главная',
	'nav.piano': 'Пиано-ролл',
	'nav.drums': 'Ударные',
	'nav.arrangement': 'Аранжировка',
	'nav.soundSculpt': 'Скульптор звука',
	'nav.layers': 'Слои',
	'nav.context': 'Параметры',
	'home.eyebrow': 'Студия электронной музыки',
	'home.title': 'Начни с ощущения.',
	'home.description': 'Собери первый луп, не переводя идею на язык звукорежиссуры.',
	'home.newProject': 'Создать новую композицию',
	'home.openProject': 'Открыть проект',
	'home.recent': 'Недавние композиции',
	'home.empty': 'Здесь появятся недавние композиции.',
	'home.recentDetail': '{{bpm}} BPM · {{count}} слоёв',
	'firstLayer.eyebrow': 'Спокойный первый шаг',
	'firstLayer.title': 'Что станет основой идеи?',
	'firstLayer.description': 'Выбери музыкальную роль. Звук можно изменить в любой момент.',
	'firstLayer.melody': 'Мелодия',
	'firstLayer.chords': 'Аккорды',
	'firstLayer.bass': 'Бас',
	'firstLayer.drums': 'Ритм',
	'firstLayer.melodyDescription': 'Линия, которую хочется запомнить',
	'firstLayer.chordsDescription': 'Цвет и эмоциональный вес',
	'firstLayer.bassDescription': 'Уверенный низкий пульс',
	'firstLayer.drumsDescription': 'Движение и время',
	'soundChooser.title': 'Выбери характер',
	'soundChooser.description': 'Звуки сначала собраны по ощущениям, а не по терминам синтеза.',
	'soundChooser.palette': 'Палитра 01',
	'soundChooser.warm': 'Тёплый',
	'soundChooser.clear': 'Ясный',
	'soundChooser.deep': 'Глубокий',
	'soundChooser.grainy': 'Зернистый',
	'soundChooser.preview': 'Прослушать звук',
	'soundChooser.feltSignalDescription': 'Мягкий край · близкий и живой',
	'soundChooser.clearGlassDescription': 'Открытый верх · спокойное затухание',
	'soundChooser.lowEmberDescription': 'Плотный центр · тихое движение',
	'soundChooser.paperStarsDescription': 'Сухая текстура · неровное свечение',
	'pianoRoll.title': 'Пиано-ролл',
	'pianoRoll.subtitle': 'Придай фразе форму',
	'pianoRoll.addNote': 'Добавить ноту',
	'pianoRoll.velocity': 'Энергия',
	'pianoRoll.noteAtBeat': '{{pitch}}, доля {{beat}}',
	'pianoRoll.hint': 'Tab перемещает по нотам · Enter удаляет выбранную ноту',
	'drums.title': 'Ударные',
	'drums.subtitle': 'Собери пульс',
	'drums.kick': 'Бочка',
	'drums.snare': 'Малый барабан',
	'drums.hat': 'Хай-хэт',
	'drums.clap': 'Хлопок',
	'drums.steps': '{{count}} шагов',
	'drums.stepLabel': '{{instrument}}, шаг {{step}}',
	'drums.hint': 'Tab перемещает по шагам · Пробел включает удар',
	'arrangement.title': 'Аранжировка',
	'arrangement.subtitle': 'Преврати идею в историю',
	'arrangement.intro': 'Вступление',
	'arrangement.main': 'Основная часть',
	'arrangement.break': 'Пауза',
	'arrangement.outro': 'Финал',
	'arrangement.bars': '{{count}} тактов',
	'sculpt.title': 'Скульптор звука',
	'sculpt.subtitle': 'Опиши движение, вес и пространство',
	'sculpt.brightness': 'Яркость',
	'sculpt.movement': 'Движение',
	'sculpt.space': 'Пространство',
	'sculpt.texture': 'Текстура',
	'layers.title': 'Слои',
	'layers.add': 'Добавить слой',
	'layers.melody': 'Стеклянная мелодия',
	'layers.chords': 'Тёплые аккорды',
	'layers.bass': 'Низкий пульс',
	'layers.drums': 'Мягкие ударные',
	'context.title': 'Параметры',
	'context.sound': 'Звук',
	'context.feel': 'Характер',
	'context.pattern': 'Паттерн',
	'context.velocity': 'Энергия',
	'context.feltSignalDescription': 'Тёплый · мягкий край',
	'context.clearGlassDescription': 'Ясный · плавное затухание',
	'context.lowEmberDescription': 'Глубокий · спокойное движение',
	'context.enginePending': 'Изменения остаются мягкими, пока аудиодвижок не подключён.',
	'transport.play': 'Воспроизвести',
	'transport.pause': 'Пауза',
	'transport.stop': 'Остановить',
	'transport.record': 'Записать',
	'transport.tempo': 'Темп',
	'transport.position': 'Позиция',
	'transport.loop': 'Зациклить',
	'transport.audioShared': 'Общее аудио',
	'transport.toolbar': 'Транспорт',
	'engine.ready': 'Состояние аудиодвижка: готов',
	'settings.sessionOnly': 'Сохранено на эту сессию',
	'settings.loading': 'Настройки сохраняются',
	'settings.saved': 'Настройки сохранены',
	'settings.failed': 'Не удалось сохранить настройки',
	'window.minimize': 'Свернуть окно',
	'window.controls': 'Управление окном',
	'window.maximize': 'Развернуть окно',
	'window.restore': 'Восстановить окно',
	'window.close': 'Закрыть окно',
	'layout.openNavigation': 'Открыть навигацию',
	'layout.openContext': 'Открыть параметры',
	'layout.closeDrawer': 'Закрыть панель',
	'command.palette': 'Палитра команд',
	'command.shortcut': 'Сочетание клавиш: {{shortcut}}'
} as const satisfies LocalizationCatalog)

export const spanishCatalog = Object.freeze({
	'app.name': 'Tiempio',
	'app.tagline': 'Crea la música que ya puedes oír.',
	'app.desktop': 'Estudio de escritorio',
	'app.web': 'Bloc de ideas web',
	'common.close': 'Cerrar',
	'common.open': 'Abrir',
	'common.back': 'Volver',
	'common.add': 'Añadir',
	'common.more': 'Más',
	'common.settings': 'Ajustes',
	'common.language': 'Idioma',
	'common.theme': 'Apariencia',
	'common.system': 'Sistema',
	'common.light': 'Claro',
	'common.dark': 'Oscuro',
	'common.notAvailable': 'Aún no disponible',
	'nav.studio': 'Estudio',
	'nav.home': 'Inicio',
	'nav.piano': 'Piano roll',
	'nav.drums': 'Batería',
	'nav.arrangement': 'Arreglo',
	'nav.soundSculpt': 'Escultura sonora',
	'nav.layers': 'Capas',
	'nav.context': 'Contexto',
	'home.eyebrow': 'Estudio de música electrónica',
	'home.title': 'Empieza con una sensación.',
	'home.description': 'Crea un primer loop sin traducir tu idea al lenguaje de la ingeniería.',
	'home.newProject': 'Crear una pieza nueva',
	'home.openProject': 'Abrir un proyecto',
	'home.recent': 'Piezas recientes',
	'home.empty': 'Tus piezas recientes aparecerán aquí.',
	'home.recentDetail': '{{bpm}} BPM · {{count}} capas',
	'firstLayer.eyebrow': 'Un primer paso tranquilo',
	'firstLayer.title': '¿Qué llevará la idea?',
	'firstLayer.description':
		'Elige un papel musical. Puedes cambiar el sonido en cualquier momento.',
	'firstLayer.melody': 'Melodía',
	'firstLayer.chords': 'Acordes',
	'firstLayer.bass': 'Bajo',
	'firstLayer.drums': 'Ritmo',
	'firstLayer.melodyDescription': 'Una línea para recordar',
	'firstLayer.chordsDescription': 'Color y peso emocional',
	'firstLayer.bassDescription': 'Un pulso firme',
	'firstLayer.drumsDescription': 'Movimiento y tiempo',
	'soundChooser.title': 'Elige un carácter',
	'soundChooser.description':
		'Los sonidos se agrupan por sensaciones antes que por términos de síntesis.',
	'soundChooser.palette': 'Paleta 01',
	'soundChooser.warm': 'Cálido',
	'soundChooser.clear': 'Claro',
	'soundChooser.deep': 'Profundo',
	'soundChooser.grainy': 'Granulado',
	'soundChooser.preview': 'Escuchar sonido',
	'soundChooser.feltSignalDescription': 'Borde suave · cercano y humano',
	'soundChooser.clearGlassDescription': 'Agudos abiertos · caída paciente',
	'soundChooser.lowEmberDescription': 'Centro denso · movimiento sereno',
	'soundChooser.paperStarsDescription': 'Textura seca · brillo irregular',
	'pianoRoll.title': 'Piano roll',
	'pianoRoll.subtitle': 'Da forma a la frase',
	'pianoRoll.addNote': 'Añadir nota',
	'pianoRoll.velocity': 'Energía',
	'pianoRoll.noteAtBeat': '{{pitch}}, pulso {{beat}}',
	'pianoRoll.hint': 'Tab recorre las notas · Enter elimina la nota seleccionada',
	'drums.title': 'Batería',
	'drums.subtitle': 'Construye el pulso',
	'drums.kick': 'Bombo',
	'drums.snare': 'Caja',
	'drums.hat': 'Charles',
	'drums.clap': 'Palmada',
	'drums.steps': '{{count}} pasos',
	'drums.stepLabel': '{{instrument}}, paso {{step}}',
	'drums.hint': 'Tab recorre los pasos · Espacio activa un golpe',
	'arrangement.title': 'Arreglo',
	'arrangement.subtitle': 'Dale un recorrido a la idea',
	'arrangement.intro': 'Introducción',
	'arrangement.main': 'Parte principal',
	'arrangement.break': 'Pausa',
	'arrangement.outro': 'Final',
	'arrangement.bars': '{{count}} compases',
	'sculpt.title': 'Escultura sonora',
	'sculpt.subtitle': 'Describe movimiento, peso y espacio',
	'sculpt.brightness': 'Brillo',
	'sculpt.movement': 'Movimiento',
	'sculpt.space': 'Espacio',
	'sculpt.texture': 'Textura',
	'layers.title': 'Capas',
	'layers.add': 'Añadir capa',
	'layers.melody': 'Melodía de cristal',
	'layers.chords': 'Acordes cálidos',
	'layers.bass': 'Pulso grave',
	'layers.drums': 'Batería suave',
	'context.title': 'Detalles',
	'context.sound': 'Sonido',
	'context.feel': 'Carácter',
	'context.pattern': 'Patrón',
	'context.velocity': 'Energía',
	'context.feltSignalDescription': 'Cálido · borde suave',
	'context.clearGlassDescription': 'Claro · caída paciente',
	'context.lowEmberDescription': 'Profundo · movimiento sereno',
	'context.enginePending':
		'Los cambios se mantienen suaves hasta que se conecte el motor de audio.',
	'transport.play': 'Reproducir',
	'transport.pause': 'Pausa',
	'transport.stop': 'Detener',
	'transport.record': 'Grabar',
	'transport.tempo': 'Tempo',
	'transport.position': 'Posición',
	'transport.loop': 'Bucle',
	'transport.audioShared': 'Audio compartido',
	'transport.toolbar': 'Transporte',
	'engine.ready': 'Estado del motor de audio: listo',
	'settings.sessionOnly': 'Guardado durante esta sesión',
	'settings.loading': 'Guardando ajustes',
	'settings.saved': 'Ajustes guardados',
	'settings.failed': 'No se pudieron guardar los ajustes',
	'window.minimize': 'Minimizar ventana',
	'window.controls': 'Controles de ventana',
	'window.maximize': 'Maximizar ventana',
	'window.restore': 'Restaurar ventana',
	'window.close': 'Cerrar ventana',
	'layout.openNavigation': 'Abrir navegación',
	'layout.openContext': 'Abrir detalles',
	'layout.closeDrawer': 'Cerrar panel',
	'command.palette': 'Paleta de comandos',
	'command.shortcut': 'Atajo: {{shortcut}}'
} as const satisfies LocalizationCatalog)

export const catalogs = Object.freeze({
	en: englishCatalog,
	ru: russianCatalog,
	es: spanishCatalog
})
