[package]
name = "tiempio-engine-synth"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
tiempio-engine-core = { path = "../core" }
tiempio-engine-dsp = { path = "../dsp" }

[dev-dependencies]
allocation-counter = "=0.8.1"

[lints]
workspace = true
