// Generated by scripts/generate-engine-protocol.mjs. Do not edit directly.

pub const ENGINE_PROTOCOL_SCHEMA_VERSION: u32 = 1;
pub const ENGINE_PROTOCOL_VERSION: u32 = 2;
pub const ENGINE_PROTOCOL_MAX_FRAME_BYTES: usize = 262_144;
pub const ENGINE_PROTOCOL_MAX_PAYLOAD_BYTES: usize = 196_608;
pub const ENGINE_PROTOCOL_MAX_IDENTIFIER_BYTES: usize = 128;
pub const ENGINE_PROTOCOL_MAX_BATCH_ITEMS: usize = 4_096;
pub const ENGINE_PROTOCOL_MAX_JSON_DEPTH: usize = 32;
pub const ENGINE_PROTOCOL_MAX_ENGINE_LAYERS: usize = 32;
pub const ENGINE_PROTOCOL_MAX_TEMPO_POINTS: usize = 256;
pub const ENGINE_PROTOCOL_MAX_MUSICAL_EVENTS: usize = 4_096;
pub const ENGINE_PROTOCOL_MAX_PREPARED_ACTIONS: usize = 8_192;
pub const ENGINE_PROTOCOL_MAX_ACTIONS_PER_BLOCK: usize = 512;
pub const ENGINE_PROTOCOL_MAX_VOICES: usize = 64;
pub const ENGINE_PROTOCOL_MAX_BLOCK_FRAMES: usize = 2_048;
pub const ENGINE_PROTOCOL_MIN_SAMPLE_RATE: usize = 8_000;
pub const ENGINE_PROTOCOL_MAX_SAMPLE_RATE: usize = 192_000;
pub const ENGINE_PROTOCOL_MAX_OFFLINE_SECONDS: usize = 600;

pub const ENGINE_COMMAND_TYPES: &[&str] = &[
    "handshake",
    "configure-audio",
    "start-audio",
    "stop-audio",
    "load-render-plan",
    "apply-render-plan-delta",
    "play",
    "stop",
    "seek",
    "set-loop",
    "note-on",
    "note-off",
    "preview-macro",
    "commit-macro",
    "request-diagnostics",
    "refresh-devices",
    "start-offline-render",
    "cancel-offline-render",
    "shutdown",
    "ping",
];

pub const ENGINE_EVENT_TYPES: &[&str] = &[
    "ready",
    "capabilities",
    "render-plan-acknowledged",
    "transport-snapshot",
    "meter-snapshot",
    "audio-devices-changed",
    "active-device-changed",
    "midi-captured",
    "diagnostic",
    "offline-render-progress",
    "offline-render-completed",
    "fatal-error",
    "pong",
    "audio-health",
];

pub const ENGINE_CAPABILITY_CODES: &[&str] = &[
    "protocol.typed-json",
    "render-plan.full",
    "transport.basic",
    "transport.loop",
    "synth.bass.deep",
    "audition.notes",
    "diagnostics.health",
    "render.offline",
    "supervision.heartbeat",
    "audio.native.shared",
    "audio.devices",
];

pub const ENGINE_DIAGNOSTIC_CODES: &[&str] = &[
    "protocol.version-mismatch",
    "protocol.frame-too-large",
    "protocol.invalid-envelope",
    "protocol.invalid-sequence",
    "protocol.unsupported-command",
    "engine.unavailable",
    "engine.invalid-plan",
    "engine.stale-revision",
    "engine.unsupported-source",
    "engine.limit-exceeded",
    "audio.suspended",
    "audio.device-unavailable",
    "audio.device-lost",
    "audio.configuration-unsupported",
    "audio.start-failed",
    "audio.output-muted",
    "audio.render-overload",
    "audio.non-finite-output",
    "offline.canceled",
];
