// Generated by scripts/generate-engine-protocol.mjs. Do not edit directly.

pub const ENGINE_PROTOCOL_SCHEMA_VERSION: u32 = 1;
pub const ENGINE_PROTOCOL_VERSION: u32 = 1;
pub const ENGINE_PROTOCOL_MAX_FRAME_BYTES: usize = 262144;
pub const ENGINE_PROTOCOL_MAX_PAYLOAD_BYTES: usize = 196608;
pub const ENGINE_PROTOCOL_MAX_IDENTIFIER_BYTES: usize = 128;
pub const ENGINE_PROTOCOL_MAX_BATCH_ITEMS: usize = 4096;

pub const ENGINE_COMMAND_TYPES: &[&str] = &[
    "handshake",
    "configure-audio",
    "start-audio",
    "stop-audio",
    "load-render-plan",
    "apply-render-plan-delta",
    "play",
    "stop",
    "seek",
    "set-loop",
    "note-on",
    "note-off",
    "preview-macro",
    "commit-macro",
    "request-diagnostics",
    "refresh-devices",
    "start-offline-render",
    "cancel-offline-render",
    "shutdown",
];

pub const ENGINE_EVENT_TYPES: &[&str] = &[
    "ready",
    "capabilities",
    "render-plan-acknowledged",
    "transport-snapshot",
    "meter-snapshot",
    "active-device-changed",
    "midi-captured",
    "diagnostic",
    "offline-render-progress",
    "offline-render-completed",
    "fatal-error",
];

pub const ENGINE_DIAGNOSTIC_CODES: &[&str] = &[
    "protocol.version-mismatch",
    "protocol.frame-too-large",
    "protocol.invalid-envelope",
    "engine.unavailable",
    "audio.suspended",
    "audio.device-unavailable",
    "audio.output-muted",
    "audio.render-overload",
];
