// Generated by scripts/generate-engine-protocol.mjs. Do not edit directly.

pub const ENGINE_PROTOCOL_SCHEMA_VERSION: u32 = 1;
pub const ENGINE_PROTOCOL_VERSION: u32 = 4;
pub const ENGINE_PROTOCOL_MAX_FRAME_BYTES: usize = 262_144;
pub const ENGINE_PROTOCOL_MAX_PAYLOAD_BYTES: usize = 196_608;
pub const ENGINE_PROTOCOL_MAX_IDENTIFIER_BYTES: usize = 128;
pub const ENGINE_PROTOCOL_MAX_BATCH_ITEMS: usize = 4_096;
pub const ENGINE_PROTOCOL_MAX_JSON_DEPTH: usize = 32;
pub const ENGINE_PROTOCOL_MAX_ENGINE_LAYERS: usize = 32;
pub const ENGINE_PROTOCOL_MAX_TEMPO_POINTS: usize = 256;
pub const ENGINE_PROTOCOL_MAX_METER_POINTS: usize = 256;
pub const ENGINE_PROTOCOL_MAX_MUSICAL_EVENTS: usize = 4_096;
pub const ENGINE_PROTOCOL_MAX_PREPARED_ACTIONS: usize = 8_192;
pub const ENGINE_PROTOCOL_MAX_PREPARED_BEATS: usize = 8_192;
pub const ENGINE_PROTOCOL_MAX_ACTIONS_PER_BLOCK: usize = 512;
pub const ENGINE_PROTOCOL_MAX_VOICES: usize = 64;
pub const ENGINE_PROTOCOL_MAX_BLOCK_FRAMES: usize = 2_048;
pub const ENGINE_PROTOCOL_MIN_SAMPLE_RATE: usize = 8_000;
pub const ENGINE_PROTOCOL_MAX_SAMPLE_RATE: usize = 192_000;
pub const ENGINE_PROTOCOL_MAX_OFFLINE_SECONDS: usize = 600;
pub const ENGINE_PROTOCOL_MAX_PREVIEW_EVENTS: usize = 64;
pub const ENGINE_PROTOCOL_MAX_PREVIEW_CHORD_SIZE: usize = 8;
pub const ENGINE_PROTOCOL_MAX_PREVIEW_DURATION_MS: usize = 5_000;

#[derive(Clone, Debug, serde::Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ProtocolLimits {
    pub max_frame_bytes: usize,
    pub max_payload_bytes: usize,
    pub max_identifier_bytes: usize,
    pub max_batch_items: usize,
    pub max_json_depth: usize,
    pub max_engine_layers: usize,
    pub max_tempo_points: usize,
    pub max_meter_points: usize,
    pub max_musical_events: usize,
    pub max_prepared_actions: usize,
    pub max_prepared_beats: usize,
    pub max_actions_per_block: usize,
    pub max_voices: usize,
    pub max_block_frames: usize,
    pub min_sample_rate: usize,
    pub max_sample_rate: usize,
    pub max_offline_seconds: usize,
    pub max_preview_events: usize,
    pub max_preview_chord_size: usize,
    pub max_preview_duration_ms: usize,
}

impl ProtocolLimits {
    #[must_use]
    pub const fn current() -> Self {
        Self {
            max_frame_bytes: ENGINE_PROTOCOL_MAX_FRAME_BYTES,
            max_payload_bytes: ENGINE_PROTOCOL_MAX_PAYLOAD_BYTES,
            max_identifier_bytes: ENGINE_PROTOCOL_MAX_IDENTIFIER_BYTES,
            max_batch_items: ENGINE_PROTOCOL_MAX_BATCH_ITEMS,
            max_json_depth: ENGINE_PROTOCOL_MAX_JSON_DEPTH,
            max_engine_layers: ENGINE_PROTOCOL_MAX_ENGINE_LAYERS,
            max_tempo_points: ENGINE_PROTOCOL_MAX_TEMPO_POINTS,
            max_meter_points: ENGINE_PROTOCOL_MAX_METER_POINTS,
            max_musical_events: ENGINE_PROTOCOL_MAX_MUSICAL_EVENTS,
            max_prepared_actions: ENGINE_PROTOCOL_MAX_PREPARED_ACTIONS,
            max_prepared_beats: ENGINE_PROTOCOL_MAX_PREPARED_BEATS,
            max_actions_per_block: ENGINE_PROTOCOL_MAX_ACTIONS_PER_BLOCK,
            max_voices: ENGINE_PROTOCOL_MAX_VOICES,
            max_block_frames: ENGINE_PROTOCOL_MAX_BLOCK_FRAMES,
            min_sample_rate: ENGINE_PROTOCOL_MIN_SAMPLE_RATE,
            max_sample_rate: ENGINE_PROTOCOL_MAX_SAMPLE_RATE,
            max_offline_seconds: ENGINE_PROTOCOL_MAX_OFFLINE_SECONDS,
            max_preview_events: ENGINE_PROTOCOL_MAX_PREVIEW_EVENTS,
            max_preview_chord_size: ENGINE_PROTOCOL_MAX_PREVIEW_CHORD_SIZE,
            max_preview_duration_ms: ENGINE_PROTOCOL_MAX_PREVIEW_DURATION_MS,
        }
    }
}

pub const ENGINE_COMMAND_TYPES: &[&str] = &[
    "handshake",
    "configure-audio",
    "start-audio",
    "stop-audio",
    "load-render-plan",
    "apply-render-plan-delta",
    "play",
    "stop",
    "seek",
    "set-loop",
    "set-metronome-enabled",
    "set-metronome-volume",
    "note-on",
    "note-off",
    "start-preview",
    "cancel-preview",
    "preview-macro",
    "commit-macro",
    "request-diagnostics",
    "refresh-devices",
    "start-offline-render",
    "cancel-offline-render",
    "shutdown",
    "ping",
];

pub const ENGINE_EVENT_TYPES: &[&str] = &[
    "ready",
    "capabilities",
    "render-plan-acknowledged",
    "transport-snapshot",
    "meter-snapshot",
    "preview-started",
    "preview-state",
    "preview-ended",
    "audio-devices-changed",
    "active-device-changed",
    "midi-captured",
    "diagnostic",
    "offline-render-progress",
    "offline-render-completed",
    "fatal-error",
    "pong",
    "audio-health",
];

pub const ENGINE_CAPABILITY_CODES: &[&str] = &[
    "protocol.typed-json",
    "render-plan.full",
    "transport.basic",
    "transport.loop",
    "metronome.native",
    "synth.bass.deep",
    "audition.notes",
    "preview.programs",
    "diagnostics.health",
    "render.offline",
    "supervision.heartbeat",
    "audio.native.shared",
    "audio.devices",
];

pub const ENGINE_DIAGNOSTIC_CODES: &[&str] = &[
    "protocol.version-mismatch",
    "protocol.frame-too-large",
    "protocol.invalid-envelope",
    "protocol.invalid-sequence",
    "protocol.unsupported-command",
    "engine.unavailable",
    "engine.invalid-plan",
    "engine.stale-revision",
    "engine.unsupported-source",
    "engine.limit-exceeded",
    "audio.suspended",
    "audio.device-unavailable",
    "audio.device-lost",
    "audio.configuration-unsupported",
    "audio.start-failed",
    "audio.output-muted",
    "audio.render-overload",
    "audio.non-finite-output",
    "offline.canceled",
];
