export {
	createProjectFromCommand,
	previewBassMacro,
	previewSynthMacro,
	reduceProjectCommand,
	type AddLayerCommand,
	type AddNoteCommand,
	type AddSectionCommand,
	type BeginSourceNoteCommand,
	type CommitMacroCommand,
	type ConfigureLayerSoundCommand,
	type CreateProjectCommand,
	type DeleteSongInstanceCommand,
	type DeleteNoteCommand,
	type ExtendSourceMaterialCommand,
	type FinalizeSourceNoteCommand,
	type MacroPreviewResult,
	type MoveNoteCommand,
	type MoveSongInstanceCommand,
	type PlaceSongInstanceCommand,
	type ProjectCommand,
	type ProjectCommandFailure,
	type ProjectCommandFailureCode,
	type ProjectCommandResult,
	type ResizeNoteCommand,
	type ResizeSongInstanceCommand,
	type SelectCharacterCommand,
	type SetLayerPerformanceCommand,
	type SetKeyCommand,
	type SetLayerGainCommand,
	type SetLayerMuteCommand,
	type SetLayerSoloCommand,
	type SetLoopCommand,
	type SelectDrumVoiceCommand,
	type SetDrumDensityCommand,
	type SetDrumPatternCommand,
	type SetDrumSwingCommand,
	type SetTempoCommand,
	type ToggleDrumEventCommand,
	type TransposeOctaveCommand,
	type UpdateNoteCommand
} from './commands.js'
export {
	createAssetReference,
	createDrumMaterial,
	createDrumEvent,
	createLayer,
	createMidiMaterial,
	createMidiNote,
	createProject,
	createSection,
	createSongInstance,
	projectKey,
	type CreateAssetReferenceInput,
	type CreateDrumMaterialInput,
	type CreateDrumEventInput,
	type CreateLayerInput,
	type CreateMidiMaterialInput,
	type CreateMidiNoteInput,
	type CreateProjectInput,
	type CreateSectionInput,
	type CreateSongInstanceInput
} from './factories.js'
export { cloneAndFreeze } from './immutable.js'
export { loadProjectDocument, type ProjectLoadResult } from './project-loader.js'
export {
	assetId,
	defaultTicksPerQuarter,
	drumEventId,
	engineModelVersion,
	isOpaqueId,
	layerId,
	macroMappingVersion,
	midiPitch,
	noteId,
	patchModelVersion,
	projectCoreVersion,
	projectId,
	projectLimits,
	projectSchemaVersion,
	projectTick,
	sectionId,
	songInstanceId,
	type AssetId,
	type BassMacroId,
	type BassPresetId,
	type DrumMaterial,
	type DrumEvent,
	type DrumEventId,
	type DrumInstrument,
	type DrumKitId,
	type DrumPatternCharacter,
	type DrumSource,
	type DrumVoiceVariantId,
	type KeyMode,
	type LayerPerformanceMapping,
	type LayerId,
	type LayerSource,
	type LayerMaterial,
	type MeterPoint,
	type MidiMaterial,
	type MidiNote,
	type MidiPitch,
	type NoteId,
	type ProjectAssetReference,
	type ProjectDocument,
	type ProjectId,
	type ProjectKey,
	type ProjectLayer,
	type ProjectLoop,
	type ProjectRole,
	type ProjectSection,
	type ProjectSong,
	type ProjectTick,
	type ProjectTransport,
	type ReferenceSource,
	type ResolvedDrumKitPatch,
	type ResolvedDrumVoicePatch,
	type ResolvedSynthPatch,
	type SectionId,
	type SongInstance,
	type SongInstanceId,
	type SemanticSynthMacros,
	type SoundFamily,
	type SynthSource,
	type SynthInstrumentState,
	type SynthMacroId,
	type SynthPresetId,
	type SynthWaveform,
	type TempoPoint
} from './model.js'
export {
	assertMacroValue,
	createCleanPulseDrumSource,
	createDeepBassInstrument,
	createSynthInstrument,
	defaultDrumVoiceVariants,
	deepBassDefaultMacros,
	deepBassPresetRevision,
	resolveDeepBassPatch,
	resolveDrumKitPatch,
	resolveSynthPatch,
	drumVoiceVariantCatalog,
	drumVoiceVariantsFor,
	synthPresetCatalog,
	synthPresetDefinition,
	synthPresetRevision,
	synthPresetsForFamily,
	type SynthPresetDefinition,
	updateDeepBassMacro,
	updateDrumVoiceVariant,
	updateSynthMacro
} from './presets.js'
export {
	compileEngineWireRenderPlan,
	compileEngineWireSynthPatch,
	compileProjectRenderPlan,
	renderPlanVersion,
	type EngineWirePlanCompilationResult,
	type ProjectRenderPlan,
	type RenderPlanDrumEvent,
	type RenderPlanEvent,
	type RenderPlanLayer,
	type RenderPlanMidiEvent,
	type RenderPlanResult
} from './render-plan.js'
export {
	defaultProjectHistoryCapacity,
	maximumProjectHistoryCapacity,
	ProjectSession,
	ProjectSessionError,
	type ProjectDispatchOptions,
	type PreparedProjectTransaction,
	type ProjectSessionErrorCode,
	type ProjectSessionSnapshot,
	type RevisionOperation
} from './session.js'
export {
	assertValidProject,
	ProjectValidationError,
	validateProjectDocument,
	type ProjectValidationIssue,
	type ProjectValidationIssueCode,
	type ProjectValidationResult
} from './validation.js'
