export {
	createProjectFromCommand,
	previewBassMacro,
	previewSynthMacro,
	reduceProjectCommand,
	type AddLayerCommand,
	type AddNoteCommand,
	type AddSectionCommand,
	type CommitMacroCommand,
	type ConfigureLayerSoundCommand,
	type CreateProjectCommand,
	type DeleteClipCommand,
	type DeleteNoteCommand,
	type MacroPreviewResult,
	type MoveNoteCommand,
	type PlaceClipCommand,
	type ProjectCommand,
	type ProjectCommandFailure,
	type ProjectCommandFailureCode,
	type ProjectCommandResult,
	type ResizeNoteCommand,
	type SelectCharacterCommand,
	type SetLayerPerformanceCommand,
	type SetKeyCommand,
	type SetLayerGainCommand,
	type SetLayerMuteCommand,
	type SetLayerSoloCommand,
	type SetLoopCommand,
	type SelectDrumVoiceCommand,
	type SetDrumDensityCommand,
	type SetDrumPatternCommand,
	type SetDrumSwingCommand,
	type SetTempoCommand,
	type ToggleDrumEventCommand,
	type TransposeOctaveCommand,
	type UpdateNoteCommand
} from './commands.js'
export {
	createAssetReference,
	createDrumClip,
	createDrumEvent,
	createLayer,
	createMidiClip,
	createMidiNote,
	createProject,
	createSection,
	projectKey,
	type CreateAssetReferenceInput,
	type CreateDrumClipInput,
	type CreateDrumEventInput,
	type CreateLayerInput,
	type CreateMidiClipInput,
	type CreateMidiNoteInput,
	type CreateProjectInput,
	type CreateSectionInput
} from './factories.js'
export { cloneAndFreeze } from './immutable.js'
export { loadProjectDocument, type ProjectLoadResult } from './migrations.js'
export {
	assetId,
	clipId,
	defaultTicksPerQuarter,
	drumEventId,
	engineModelVersion,
	firstProjectSchemaVersion,
	isOpaqueId,
	layerId,
	legacyProjectSchemaVersion,
	macroMappingVersion,
	legacyEngineModelVersion,
	legacyMacroMappingVersion,
	legacyPatchModelVersion,
	midiPitch,
	noteId,
	patchModelVersion,
	projectCoreVersion,
	projectId,
	projectLimits,
	projectSchemaVersion,
	previousProjectSchemaVersion,
	projectTick,
	sectionId,
	type AssetId,
	type BassInstrumentStateV1,
	type BassMacroId,
	type BassPresetId,
	type ClipId,
	type DrumClip,
	type DrumEvent,
	type DrumEventId,
	type DrumInstrument,
	type DrumKitId,
	type DrumPatternCharacter,
	type DrumSource,
	type DrumVoiceVariantId,
	type KeyMode,
	type LayerPerformanceMapping,
	type LayerId,
	type LayerSource,
	type LegacyProjectDocumentV0,
	type MeterPoint,
	type MidiClip,
	type MidiNote,
	type MidiPitch,
	type NoteId,
	type ProjectAssetReference,
	type ProjectClip,
	type ProjectDocument,
	type ProjectDocumentV1,
	type ProjectDocumentV2,
	type ProjectDocumentV3,
	type ProjectId,
	type ProjectKey,
	type ProjectLayer,
	type ProjectLoop,
	type ProjectRole,
	type ProjectSection,
	type ProjectTick,
	type ProjectTransport,
	type ReferenceSource,
	type ResolvedBassPatchV1,
	type ResolvedDrumKitPatchV2,
	type ResolvedDrumVoicePatchV2,
	type ResolvedSynthPatchV2,
	type SectionId,
	type SemanticBassMacrosV1,
	type SemanticSynthMacrosV2,
	type SoundFamily,
	type SynthSource,
	type SynthInstrumentStateV2,
	type SynthMacroId,
	type SynthPresetId,
	type SynthWaveform,
	type TempoPoint
} from './model.js'
export {
	assertMacroValue,
	createCleanPulseDrumSource,
	createDeepBassInstrument,
	createSynthInstrument,
	defaultDrumVoiceVariants,
	deepBassDefaultMacros,
	deepBassPresetRevision,
	resolveDeepBassPatch,
	resolveDrumKitPatch,
	resolveSynthPatch,
	drumVoiceVariantCatalog,
	drumVoiceVariantsFor,
	synthPresetCatalog,
	synthPresetDefinition,
	synthPresetRevision,
	synthPresetsForFamily,
	updateDeepBassMacro,
	updateDrumVoiceVariant,
	updateSynthMacro
} from './presets.js'
export {
	compileEngineWireRenderPlan,
	compileProjectRenderPlan,
	renderPlanVersion,
	type EngineWirePlanCompilationResult,
	type ProjectRenderPlan,
	type RenderPlanDrumEvent,
	type RenderPlanEvent,
	type RenderPlanLayer,
	type RenderPlanMidiEvent,
	type RenderPlanResult
} from './render-plan.js'
export {
	defaultProjectHistoryCapacity,
	maximumProjectHistoryCapacity,
	ProjectSession,
	ProjectSessionError,
	type ProjectDispatchOptions,
	type ProjectSessionErrorCode,
	type ProjectSessionSnapshot,
	type RevisionOperation
} from './session.js'
export {
	assertValidProject,
	ProjectValidationError,
	validateProjectDocument,
	type ProjectValidationIssue,
	type ProjectValidationIssueCode,
	type ProjectValidationResult
} from './validation.js'
