export {
	createAssetReference,
	createDrumClip,
	createDrumEvent,
	createLayer,
	createMidiClip,
	createMidiNote,
	createProject,
	createSection,
	projectKey,
	type CreateAssetReferenceInput,
	type CreateDrumClipInput,
	type CreateDrumEventInput,
	type CreateLayerInput,
	type CreateMidiClipInput,
	type CreateMidiNoteInput,
	type CreateProjectInput,
	type CreateSectionInput
} from './factories.js'
export { cloneAndFreeze } from './immutable.js'
export { loadProjectDocument, type ProjectLoadResult } from './migrations.js'
export {
	assetId,
	clipId,
	defaultTicksPerQuarter,
	drumEventId,
	engineModelVersion,
	isOpaqueId,
	layerId,
	legacyProjectSchemaVersion,
	macroMappingVersion,
	midiPitch,
	noteId,
	patchModelVersion,
	projectCoreVersion,
	projectId,
	projectLimits,
	projectSchemaVersion,
	projectTick,
	sectionId,
	type AssetId,
	type BassInstrumentStateV1,
	type BassMacroId,
	type BassPresetId,
	type ClipId,
	type DrumClip,
	type DrumEvent,
	type DrumEventId,
	type DrumInstrument,
	type DrumSource,
	type KeyMode,
	type LayerId,
	type LayerSource,
	type LegacyProjectDocumentV0,
	type MeterPoint,
	type MidiClip,
	type MidiNote,
	type MidiPitch,
	type NoteId,
	type ProjectAssetReference,
	type ProjectClip,
	type ProjectDocument,
	type ProjectDocumentV1,
	type ProjectId,
	type ProjectKey,
	type ProjectLayer,
	type ProjectLoop,
	type ProjectRole,
	type ProjectSection,
	type ProjectTick,
	type ProjectTransport,
	type ReferenceSource,
	type ResolvedBassPatchV1,
	type SectionId,
	type SemanticBassMacrosV1,
	type SynthSource,
	type TempoPoint
} from './model.js'
export {
	assertMacroValue,
	createDeepBassInstrument,
	deepBassDefaultMacros,
	deepBassPresetRevision,
	resolveDeepBassPatch,
	updateDeepBassMacro
} from './presets.js'
export {
	assertValidProject,
	ProjectValidationError,
	validateProjectDocument,
	type ProjectValidationIssue,
	type ProjectValidationIssueCode,
	type ProjectValidationResult
} from './validation.js'
